Add upgrade check warning for allocations db
Adding an upgrade check to provide awareness to the state of
the database in regards if an unexpected engine is in use or
if the character set encoding is also not UTF8.

These will raise non-fatal warnings on the upgrade status
check.

Change-Id: Ide0eb4690a056be557e5ea7d5ba5f6be37b50d0a
Story: 2010384

diff --git a/devstack/lib/ironic b/devstack/lib/ironic
--- a/devstack/lib/ironic
+++ b/devstack/lib/ironic
@@ -1924,6 +1924,11 @@ function init_ironic {
     # NOTE(rloo): We're not upgrading but want to make sure this command works,
     # even though we're not parsing the output of this command.
     $IRONIC_BIN_DIR/ironic-status upgrade check
+
+    $IRONIC_BIN_DIR/ironic-status upgrade check && ret_val=$? || ret_val=$?
+    if [ $ret_val -gt 1 ] ; then
+        die $LINENO "The `ironic-status upgrade check` command returned an error. Cannot proceed."
+    fi
 }
 
 # _ironic_bm_vm_names() - Generates list of names for baremetal VMs.
